attempt to fix circleci issue

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -25,22 +25,19 @@ jobs:
       - run:
           name: Run unit tests
           command: |
-            echo "before test"
             make test | tee ${TEST_RESULTS}/go-test.out
-            echo "after test"
-            cat ${TEST_RESULTS}/go-test.out
-            echo "before grep"
+            set +e
             grep "\-\-\- FAIL:" ${TEST_RESULTS}/go-test.out
-            echo "EXIT CODE WAS $?"
-            # if [ $? -eq 0 ];
-            # then
-            #   echo "Some test cases failed"
-            #   exit 1
-            # else
-            #   echo "All tests passed"
-            #   go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml
-            #   exit 0
-            # fi
+            if [ $? -eq 0 ];
+            then
+              echo "Some test cases failed"
+              exit 1
+            else
+              echo "All tests passed"
+              set -e
+              go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml
+              exit 0
+            fi
 
       - save_cache:
           key: v1-pkg-cache
